name: Build yay AUR Helper Package
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Build In Docker
      if: ${{ !contains(github.event.head_commit.message, '[no build]') }}
      run: |
        BUILDUSER=ltsbuilder
        BUILDGROUP=lts
        HOSTNAME=kernelbuild
        cat << EOF > entrypoint.sh
        cd /build
        timedatectl set-timezone Asia/Kolkata
        groupadd -r $BUILDGROUP
        useradd $BUILDUSER -g $BUILDGROUP -m
        passwd -d $BUILDUSER
        pacman -Syu --noconfirm --needed sudo base-devel git go
        printf '$BUILDUSER ALL=(ALL) ALL\\n' | tee -a /etc/sudoers
        chown -R $BUILDUSER:$BUILDGROUP ./
        sudo -u $BUILDUSER gpg --keyserver keyserver.ubuntu.com --recv-keys 38DBBDC86092693E
        sudo -u $BUILDUSER bash -c 'export MAKEFLAGS=j\$(nproc) && makepkg -sCf --noconfirm'
        EOF

        docker run -h $HOSTNAME -t -v $PWD:/build archlinux /bin/bash /build/entrypoint.sh
    
    - name: Print sha512sums
      if: ${{ !contains(github.event.head_commit.message, '[no build]') }}
      run: sha512sum *.pkg.tar.*

    - name: Upload Built Packages
      if: ${{ !contains(github.event.head_commit.message, '[no build]') }}
      uses: actions/upload-artifact@v4
      with:
        name: built-packages
        path: ${{ github.workspace }}/*.pkg.tar.*
        
    - name: Create Tag
      if: ${{ !contains(github.event.head_commit.message, '[no rel]') && !contains(github.event.head_commit.message, '[no build]') }}
      id: create_tag
      run: |
        source PKGBUILD
        echo "::set-output name=tag::${pkgver}"
        echo $pkgver $pkgrel
    - name: Release
      if: ${{ !contains(github.event.head_commit.message, '[no rel]') && !contains(github.event.head_commit.message, '[no build]') }}
      uses: softprops/action-gh-release@v1
      with:
         files: |
           ${{ github.workspace }}/*.pkg.tar.*
         tag_name: v${{ steps.create_tag.outputs.tag }}
         name: ${{ steps.create_tag.outputs.tag }} - Release
         draft: ${{ contains(github.event.head_commit.message, '[draft]') }}
         prerelease: ${{ contains(github.event.head_commit.message, '[prerel]') }}
         body: |
          This release features the default yay installer for T2 Manjaro
          Install packages with `sudo pacman -U <file>`, you can use urls or file paths.
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

